FROM spack/ubuntu-jammy

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    wget \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN spack install lammps
RUN spack install gromacs
RUN spack install cowsay

WORKDIR /code
COPY ./scripts /code/scripts
RUN git clone https://github.com/converged-computing/fractale /code/fractale && python3 -m pip install -e /code/fractale[all]
RUN git clone https://github.com/converged-computing/hpc-mcp /code/hpc-mcp && \
    cd /code/hpc-mcp && pip install .
RUN git clone https://github.com/converged-computing/flux-mcp /code/flux-mcp && \
    cd /code/flux-mcp && pip install . && pip install -r /code/scripts/requirements.txt
# RUN pip install flux-mcp
ENV SHELL=/usr/bin/bash
RUN python3 -m pip install sqlalchemy
