apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-mcp
spec:
  size: 2
  flux:
    container:
      disable: true
  containers:
    - image: ghcr.io/converged-computing/flux-mcp:spack-ubuntu-24.04
      launcher: true
      command: mcpserver start --port 8089 --host 0.0.0.0 -t http --config /code/scripts/run-spack.yaml
